#!/usr/bin/env python3
"""
fill_artistas_crm.py
Overwrites the Artistas sheet in CRM_ToT.xlsx with real verified artist data,
then runs upload_artistas.py to sync to Firestore.
"""

import subprocess
import openpyxl
from openpyxl import load_workbook
from copy import copy

XLSX = "CRM_ToT.xlsx"

artists = [
    {
        "id": "artista1",
        "nombre": "Alex Ponce",
        "ciudad": "Cuenca",
        "genero": "Pop",
        "activo_desde": "2019",
        "tipo": "Solista",
        "sello": "Independiente",
        "ranking": 1,
        "score": 95,
        "ep_label": "EP.01 · 2025",
        "ig_seguidores": "—",
        "spotify_oyentes": "—",
        "youtube_subs": "—",
        "tiktok": "—",
        "link_spotify": "",
        "link_instagram": "https://www.instagram.com/alexponcemusica/",
        "discografia": "Ser Humano (2023) | Plan (2024) | La última noche (2023) | Distancia (2020)",
        "colaboraciones": "Blanko",
        "foto_principal": "",
        "foto_1": "", "foto_2": "", "foto_3": "", "foto_4": "",
        "bio_headline": "La voz cuencana que llegó al Top 50 Global de Spotify sin el respaldo de un sello.",
        "bio_p1": "Alex Ponce nació el 23 de julio de 1998 en Cuenca, Ecuador. Su primer sencillo, "Distancia", fue lanzado en 2020 y marcó el inicio de una carrera construida desde cero, con honestidad y trabajo constante.",
        "bio_p2": "En 2023 lanzó su EP "Ser Humano", con 13 sencillos. La canción "Plan" se viralizó en TikTok y alcanzó el Top 50 Global de Spotify — un logro histórico para un artista ecuatoriano independiente.",
        "bio_p3": "Sus influencias van desde Luis Miguel y Chayanne hasta Bruno Mars, Dua Lipa y Coldplay. Esa mezcla define un sonido pop que conecta con audiencias de toda Latinoamérica.",
        "bio_p4": "LOS40 España lo reconoció como el artista promesa de Ecuador. Hoy es una de las voces más relevantes del pop ecuatoriano con proyección internacional.",
        "quote": "Una voz que nació en Cuenca y llegó más lejos que cualquier sello hubiera imaginado.",
        "siguiente_id": "artista2",
        "siguiente_nombre": "Johann Vera",
        "active": True,
        "order": 1,
        "notas": "@alexponcemusica",
    },
    {
        "id": "artista2",
        "nombre": "Johann Vera",
        "ciudad": "Guayaquil",
        "genero": "Pop",
        "activo_desde": "2005",
        "tipo": "Solista",
        "sello": "Independiente",
        "ranking": 2,
        "score": 93,
        "ep_label": "EP.02 · 2025",
        "ig_seguidores": "—",
        "spotify_oyentes": "—",
        "youtube_subs": "—",
        "tiktok": "—",
        "link_spotify": "",
        "link_instagram": "https://www.instagram.com/johannvera/",
        "discografia": "Nada importa en verdad (2024) | Donde Nací (2022) | Astronauta | Cielo | Pretty Girl | Vuelo a París",
        "colaboraciones": "Ricky Martin (mentor) | Camilo | Greeicy",
        "foto_principal": "",
        "foto_1": "", "foto_2": "", "foto_3": "", "foto_4": "",
        "bio_headline": "El ecuatoriano que ganó en Viña del Mar y se convirtió en el himno del Mundial Qatar 2022.",
        "bio_p1": "Johann Alexander Vera Tapia nació el 4 de diciembre de 1995 en Guayaquil. Comenzó su carrera a los 10 años en Factor X de RCN junto a Camilo y Greeicy, y fue finalista en La Banda, el reality creado por Ricky Martin y Simon Cowell.",
        "bio_p2": "En 2020 representó a Ecuador en el Festival Internacional de Viña del Mar, ganando la Gaviota de Plata — solo el segundo ecuatoriano en lograrlo. Su canción "Donde Nací" se convirtió en el himno no oficial de la selección ecuatoriana en el Mundial Qatar 2022.",
        "bio_p3": "Ha participado en series de Disney Channel y Nickelodeon, y protagonizó proyectos cinematográficos internacionales. En 2025 confirmó su debut en una película internacional interpretando a un cocinero.",
        "bio_p4": "Con su EP "Nada importa en verdad" (2024), Johann inicia su etapa más personal y honesta, conectando con una generación que busca autenticidad en la música latina.",
        "quote": "Del escenario de Viña del Mar a las canchas del Mundial — Johann Vera es el sonido de Ecuador al mundo.",
        "siguiente_id": "artista3",
        "siguiente_nombre": "Mar Rendón",
        "active": True,
        "order": 2,
        "notas": "@johannvera",
    },
    {
        "id": "artista3",
        "nombre": "Mar Rendón",
        "ciudad": "Guayaquil",
        "genero": "Pop-Rock",
        "activo_desde": "2020",
        "tipo": "Solista",
        "sello": "Intergroup Records",
        "ranking": 3,
        "score": 91,
        "ep_label": "EP.03 · 2025",
        "ig_seguidores": "370K",
        "spotify_oyentes": "—",
        "youtube_subs": "—",
        "tiktok": "—",
        "link_spotify": "",
        "link_instagram": "https://www.instagram.com/marrendonmusica/",
        "discografia": "Si No Es de Ti | Eres Tú | Legally Blonde (musical 2024)",
        "colaboraciones": "",
        "foto_principal": "",
        "foto_1": "", "foto_2": "", "foto_3": "", "foto_4": "",
        "bio_headline": "La mezzo-soprano guayaquileña que ganó dos Heat Latin Awards y apareció en Marie Claire.",
        "bio_p1": "María del Mar Rendón Kalil nació el 10 de noviembre de 2002 en Guayaquil. Ganó reconocimiento internacional en La Academia de TV Azteca, donde su voz de mezzo-soprano la distinguió de inmediato del resto de participantes.",
        "bio_p2": "Ganadora de dos Heat Latin Awards como mejor artista Rock, Mar es desde 2022 la artista femenina más escuchada en radios ecuatorianas. En 2025 firmó contrato con Intergroup Records, consolidando su carrera a nivel regional.",
        "bio_p3": "Primera ecuatoriana en aparecer en la sección de moda de la revista internacional Marie Claire. En septiembre de 2024 protagonizó su primer papel estelar en el musical "Legally Blonde".",
        "bio_p4": "Con más de 370K seguidores en Instagram y una carrera que cruza música, teatro y moda, Mar Rendón representa la nueva generación de artistas ecuatorianas que no se limitan a un solo escenario.",
        "quote": "Dos Heat Latin Awards, Marie Claire y el escenario del musical — Mar Rendón no conoce límites.",
        "siguiente_id": "artista4",
        "siguiente_nombre": "Jombriel",
        "active": True,
        "order": 3,
        "notas": "@marrendonmusica",
    },
    {
        "id": "artista4",
        "nombre": "Jombriel",
        "ciudad": "Esmeraldas",
        "genero": "Urbano / Trap",
        "activo_desde": "2020",
        "tipo": "Solista",
        "sello": "Independiente",
        "ranking": 4,
        "score": 99,
        "ep_label": "EP.04 · 2025",
        "ig_seguidores": "—",
        "spotify_oyentes": "—",
        "youtube_subs": "—",
        "tiktok": "—",
        "link_spotify": "",
        "link_instagram": "https://www.instagram.com/jombriel/",
        "discografia": "Vitamina (2025) | Parte y Choke | Modo Marroneo (2020)",
        "colaboraciones": "Nicki Nicole | Ryan Castro | Alex Krack",
        "foto_principal": "",
        "foto_1": "", "foto_2": "", "foto_3": "", "foto_4": "",
        "bio_headline": "349 millones de streams y el primer Top 1 de Spotify Ecuador — Jombriel es el más grande del urbano ecuatoriano.",
        "bio_p1": "Jonathan Cedeño Romero, conocido como Jombriel, nació el 5 de mayo de 2003 en Esmeraldas. Comenzó en el freestyle a los 17 años y su primer sencillo "Modo Marroneo" (2020) lo estableció como una fuerza emergente del urbano ecuatoriano.",
        "bio_p2": "Su canción "Parte y Choke" se volvió viral cuando Nicki Nicole publicó un TikTok bailándola — 1.9 millones de likes y 15.4 millones de vistas. El remix con Ryan Castro y Alex Krack consolidó su nombre en toda Latinoamérica.",
        "bio_p3": "En febrero de 2025 lanzó "Vitamina", que acumuló 349 millones de streams — cifra histórica para un solista ecuatoriano — y lo llevó al Top 1 de Spotify Ecuador por primera vez en la historia del país.",
        "bio_p4": "Nombrado Artista del Año en Ecuador 2025, Jombriel es la prueba de que Esmeraldas tiene el pulso más fuerte del urbano latinoamericano.",
        "quote": "349 millones de razones para que el mundo aprenda a pronunciar Esmeraldas.",
        "siguiente_id": "artista5",
        "siguiente_nombre": "Alex Krack",
        "active": True,
        "order": 4,
        "notas": "@jombriel",
    },
    {
        "id": "artista5",
        "nombre": "Alex Krack",
        "ciudad": "Esmeraldas",
        "genero": "Urbano",
        "activo_desde": "2020",
        "tipo": "Solista",
        "sello": "Universal Music Latino",
        "ranking": 5,
        "score": 90,
        "ep_label": "EP.05 · 2025",
        "ig_seguidores": "25K",
        "spotify_oyentes": "—",
        "youtube_subs": "—",
        "tiktok": "—",
        "link_spotify": "https://open.spotify.com/intl-es/artist/1YZcJWydWAbSpknMUKtD9m",
        "link_instagram": "https://www.instagram.com/alexkrack18/",
        "discografia": "Crazy QLo (2020) | Parte & Choque (remix, 2025) | Tú las Ves (álbum de Ronaldinho, 2026)",
        "colaboraciones": "Jombriel | Ryan Castro | Ronaldinho | Totoy El Frío | Natan & Shander",
        "foto_principal": "",
        "foto_1": "", "foto_2": "", "foto_3": "", "foto_4": "",
        "bio_headline": "El esmeraldeño que firmó con Universal Music y cantó en el álbum de Ronaldinho.",
        "bio_p1": "Alex Fernando Barrio Ayoví, conocido como Alex Krack, nació el 12 de noviembre de 2000 en Esmeraldas. Su pasión por la música comenzó de niño cuando recibió un piano en lugar del carro teledirigido que había pedido.",
        "bio_p2": "En 2020 co-creó "Crazy QLo" con Jombriel, canción exitosa en Ecuador. Su participación en el remix de "Parte & Choque" con Ryan Castro lo catapultó al Billboard Argentina Hot 100, atrayendo la atención de sellos internacionales.",
        "bio_p3": "Firmó con Universal Music Latino tras alcanzar el #1 en Argentina. Fue elegido para representar a Ecuador en "Camisa 10", el primer álbum musical del astro del fútbol Ronaldinho Gaúcho, con la canción "Tú las Ves".",
        "bio_p4": "Con Universal Music como respaldo y un pie en el álbum del ícono mundial del fútbol, Alex Krack es una de las proyecciones más sólidas del urbano ecuatoriano de su generación.",
        "quote": "Del barrio en Esmeraldas al álbum de Ronaldinho — Alex Krack es la siguiente gran historia del urbano.",
        "siguiente_id": "artista6",
        "siguiente_nombre": "DiCapo",
        "active": True,
        "order": 5,
        "notas": "@alexkrack18",
    },
    {
        "id": "artista6",
        "nombre": "DiCapo",
        "ciudad": "Guayaquil",
        "genero": "Pop / Soul / Funk",
        "activo_desde": "2022",
        "tipo": "Solista",
        "sello": "Independiente",
        "ranking": 6,
        "score": 88,
        "ep_label": "EP.06 · 2025",
        "ig_seguidores": "—",
        "spotify_oyentes": "—",
        "youtube_subs": "—",
        "tiktok": "—",
        "link_spotify": "",
        "link_instagram": "https://www.instagram.com/imdicapo/",
        "discografia": "Tantas cosas (2022) | Fuimos (2022)",
        "colaboraciones": "Invasores (banda anterior) | Ha$h | Morat (telonero)",
        "foto_principal": "",
        "foto_1": "", "foto_2": "", "foto_3": "", "foto_4": "",
        "bio_headline": "El pop con alma del 80, funk y jazz que nació del bolero familiar y llegó al circuito latino.",
        "bio_p1": "Diego Rafael Chiang Centanaro, conocido como DiCapo, nació en Guayaquil en 1996. Su nombre artístico es la unión de "Diego" con la expresión musical "da capo" — volver al principio. Licenciado en Artes Musicales por la Universidad Católica de Santiago de Guayaquil.",
        "bio_p2": "Creció escuchando boleros y pasillos junto a su padre músico, y desarrolló referencias desde Michael Jackson y Jamiroquai hasta The Police. Antes de su carrera solista fue finalista en La Voz Ecuador y parte de la banda Invasores, abriendo conciertos de Ha$h y Morat.",
        "bio_p3": "En 2022 lanzó su proyecto solista con el sencillo "Tantas cosas", apostando por un sonido que mezcla el espíritu retro del pop de los 80 con funk, jazz y soul latino — nostálgico sin perder frescura contemporánea.",
        "bio_p4": "Rolling Stone lo destacó entre los artistas ecuatorianos que conquistan 2025. DiCapo es la propuesta más sofisticada y de mayor profundidad del pop ecuatoriano actual.",
        "quote": "Cuando el bolero de tu padre y el funk de Jamiroquai se encuentran — ahí nace DiCapo.",
        "siguiente_id": "artista7",
        "siguiente_nombre": "Kenny Die",
        "active": True,
        "order": 6,
        "notas": "@imdicapo",
    },
    {
        "id": "artista7",
        "nombre": "Kenny Die",
        "ciudad": "Quito",
        "genero": "Trap / Reggaetón",
        "activo_desde": "2020",
        "tipo": "Solista",
        "sello": "Independiente",
        "ranking": 7,
        "score": 86,
        "ep_label": "EP.07 · 2025",
        "ig_seguidores": "70K",
        "spotify_oyentes": "—",
        "youtube_subs": "—",
        "tiktok": "—",
        "link_spotify": "https://open.spotify.com/intl-es/artist/6CHaM7DPIvAhLVOB5wNncN",
        "link_instagram": "https://www.instagram.com/kennydie777/",
        "discografia": "777 (2022) | Me Pone Crazy",
        "colaboraciones": "",
        "foto_principal": "",
        "foto_1": "", "foto_2": "", "foto_3": "", "foto_4": "",
        "bio_headline": "Trap y reggaetón sin filtros — la identidad oscura y romántica del urbano quiteño.",
        "bio_p1": "Kenny Santiago Martínez, conocido como Kenny Die, es un cantante y compositor de Quito. Desde 2020 redefine la escena urbana ecuatoriana con una fusión única de trap y reggaetón, influenciada por sus raíces latinoamericanas y una visión artística sin concesiones.",
        "bio_p2": "Su sello es una identidad marcada por lo oscuro y lo real, donde elementos románticos y crudos coexisten sin filtro. Su sencillo "Me Pone Crazy" rinde homenaje al reggaetón clásico mientras lo moderniza con producción contemporánea.",
        "bio_p3": "En 2022 lanzó su proyecto debut "777", una colección audaz que exhibe su destreza lírica y solidifica su voz en el urbano ecuatoriano. Ha acumulado millones de streams en Spotify y YouTube.",
        "bio_p4": "Posicionado como una de las propuestas ecuatorianas con mayor proyección internacional, Kenny Die lleva el sonido de Quito al mundo urbano con una propuesta auténtica y sin concesiones.",
        "quote": "Lo romántico y lo crudo en la misma canción — eso es Kenny Die, sin filtros.",
        "siguiente_id": "artista8",
        "siguiente_nombre": "Yilda",
        "active": True,
        "order": 7,
        "notas": "@kennydie777",
    },
    {
        "id": "artista8",
        "nombre": "Yilda",
        "ciudad": "Guayaquil",
        "genero": "Urbano / Pop",
        "activo_desde": "2008",
        "tipo": "Solista",
        "sello": "Independiente",
        "ranking": 8,
        "score": 87,
        "ep_label": "EP.08 · 2025",
        "ig_seguidores": "—",
        "spotify_oyentes": "—",
        "youtube_subs": "—",
        "tiktok": "—",
        "link_spotify": "",
        "link_instagram": "https://www.instagram.com/yildaoficial/",
        "discografia": "Tik Tok | Hurry | Bye Bye | Vainilla | Sí Ajá Ya Sé | Mi lado Flip",
        "colaboraciones": "Ren Kai | Ñusta",
        "foto_principal": "",
        "foto_1": "", "foto_2": "", "foto_3": "", "foto_4": "",
        "bio_headline": "De los 7 años en televisión a los Latin Grammy 2024 — Yilda es la artista que nunca paró.",
        "bio_p1": "Yilda Banchón Rivera comenzó su carrera artística a los 7 años, siendo seleccionada entre 8,000 niños para "Pequeños Brillantes" (2008). Desde entonces construyó una trayectoria que cruza la música, la actuación y el activismo social en toda Latinoamérica.",
        "bio_p2": "En 2017 ganó el primer lugar en la competencia internacional IPOP en Estados Unidos, con cuatro medallas. Sus canciones — "Tik Tok", "Hurry", "Bye Bye", "Vainilla" — la establecieron como referente del pop urbano ecuatoriano.",
        "bio_p3": "En 2024 representó a Ecuador como invitada especial en los Latin Grammy Awards en Miami. Es portavoz de UNICEF y ha actuado en la serie televisiva "Calle amores".",
        "bio_p4": "En enero de 2026 se graduó como abogada de la Universidad Católica de Guayaquil, demostrando que ser artista y profesional no son caminos distintos — son parte del mismo carácter.",
        "quote": "Veinte años en escena, cuatro medallas internacionales y un título de abogada — Yilda no elige entre sus pasiones.",
        "siguiente_id": "artista9",
        "siguiente_nombre": "Ren Kai",
        "active": True,
        "order": 8,
        "notas": "@yildaoficial",
    },
    {
        "id": "artista9",
        "nombre": "Ren Kai",
        "ciudad": "Guayaquil",
        "genero": "Latin Pop / C-Pop",
        "activo_desde": "2019",
        "tipo": "Solista",
        "sello": "Sony Music Andino / RCA China",
        "ranking": 9,
        "score": 89,
        "ep_label": "EP.09 · 2025",
        "ig_seguidores": "—",
        "spotify_oyentes": "—",
        "youtube_subs": "—",
        "tiktok": "—",
        "link_spotify": "",
        "link_instagram": "https://www.instagram.com/renkaiy/",
        "discografia": "Amor Inconcluso (2021) | Amor Infinito (2023) | Mala Idea | Hoy salí",
        "colaboraciones": "Yilda | Ñusta",
        "foto_principal": "",
        "foto_1": "", "foto_2": "", "foto_3": "", "foto_4": "",
        "bio_headline": "Mitad ecuatoriano, mitad chino — el artista que une dos culturas con un solo sonido.",
        "bio_p1": "Ren Kai Yin Moretta nació el 15 de enero de 1993 en Guayaquil, de madre ecuatoriana y padre chino. A los 9 años participaba en festivales de arte internacionales incluyendo uno en Shanghai — y desde entonces su misión fue unir culturas a través de la música.",
        "bio_p2": "En 2019, TC Televisión y Charts Ecuador lo reconocieron como Breakthrough Artist of the Year, también ganando en la categoría de Mejor Video Musical por "Mala Idea". Su álbum "Amor Inconcluso" (2021) logró 3 hits número 1 en radio.",
        "bio_p3": "En 2023 firmó con Sony Music Andino y RCA China, y lanzó "Amor Infinito" — continuación de su universo musical marcado por el carácter chino 爱 (amor). Es el único artista ecuatoriano con contrato activo en China continental.",
        "bio_p4": "Ha colaborado con Yilda y la artista quichua Ñusta en una canción que fusiona español y quichua, consolidando su rol como puente cultural en la música latinoamericana.",
        "quote": "Español, chino, quichua — Ren Kai no escoge un idioma porque su música habla todos.",
        "siguiente_id": "artista10",
        "siguiente_nombre": "Blanko",
        "active": True,
        "order": 9,
        "notas": "@renkaiy",
    },
    {
        "id": "artista10",
        "nombre": "Blanko",
        "ciudad": "Quito",
        "genero": "Pop / Reggaetón",
        "activo_desde": "2021",
        "tipo": "Solista",
        "sello": "Emporio Records",
        "ranking": 10,
        "score": 85,
        "ep_label": "EP.10 · 2025",
        "ig_seguidores": "—",
        "spotify_oyentes": "1.6M oyentes/mes",
        "youtube_subs": "—",
        "tiktok": "—",
        "link_spotify": "https://open.spotify.com/artist/2tsxhfhrjoqKy2okihHP0x",
        "link_instagram": "https://www.instagram.com/blankomusik/",
        "discografia": "Singles 2021-2024 | Colaboraciones Piso 21 | Rombai",
        "colaboraciones": "Piso 21 | Rombai | Alex Ponce | Yubeili | Vius | Sech",
        "foto_principal": "",
        "foto_1": "", "foto_2": "", "foto_3": "", "foto_4": "",
        "bio_headline": "1.6 millones de oyentes mensuales y la validación que Sech le dio desde el principio.",
        "bio_p1": "Blanko es un artista de 21 años de Quito que comenzó en 2021 creando remixes de canciones de Sech, Lunay y The Kid Laroi. Las palabras de Sech — "eres duro, sigue dándole" — marcaron un antes y un después en su carrera.",
        "bio_p2": "Su sello es la capacidad de fusionar géneros — del pop americano al reggaetón y la música mexicana nueva — creando un sonido inconfundible. Hoy 1.6 millones de personas lo escuchan mensualmente en Spotify.",
        "bio_p3": "En 2024 consolidó su lugar con colaboraciones de alto nivel: Piso 21, Rombai, Alex Ponce y Yubeili. Firmado con Emporio Records, cuyo CEO es Sebastián Jácome, su manager actual.",
        "bio_p4": "Blanko representa a una nueva generación del pop urbano quiteño que construyó su audiencia desde las plataformas digitales, sin radio ni televisión — solo música y constancia.",
        "quote": "Sech le dijo que era duro. Hoy 1.6 millones de personas le dan la razón.",
        "siguiente_id": "",
        "siguiente_nombre": "",
        "active": True,
        "order": 10,
        "notas": "@blankomusik",
    },
]

# ── Column order matches the existing header row ─────────────────
COLUMNS = [
    "id", "nombre", "ciudad", "genero", "activo_desde", "tipo", "sello",
    "ranking", "score", "ep_label",
    "ig_seguidores", "spotify_oyentes", "youtube_subs", "tiktok",
    "link_spotify", "link_instagram",
    "discografia", "colaboraciones",
    "foto_principal", "foto_1", "foto_2", "foto_3", "foto_4",
    "bio_headline", "bio_p1", "bio_p2", "bio_p3", "bio_p4",
    "quote",
    "siguiente_id", "siguiente_nombre",
    "active", "order", "notas",
]

wb = load_workbook(XLSX)
ws = wb["Artistas"]

# Clear existing data rows (keep header = row 1)
for row in ws.iter_rows(min_row=2, max_row=ws.max_row):
    for cell in row:
        cell.value = None

# Write artist rows
for i, artist in enumerate(artists, start=2):
    for col_idx, key in enumerate(COLUMNS, start=1):
        ws.cell(row=i, column=col_idx, value=artist.get(key, ""))

wb.save(XLSX)
print(f"✓ CRM_ToT.xlsx actualizado con {len(artists)} artistas reales.")

# ── Upload to Firestore ──────────────────────────────────────────
print("\nSubiendo a Firestore...\n")
result = subprocess.run(["python3", "upload_artistas.py"], capture_output=True, text=True)
print(result.stdout)
if result.returncode != 0:
    print("ERROR:", result.stderr[-500:])
